# Generated by Django 2.2.6 on 2019-10-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='titele',
            new_name='title',
        ),
    ]
