# Generated by Django 2.2.6 on 2019-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
        ),
    ]
